# Generated by Django 5.0.6 on 2024-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_aboutus", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                (
                    "image",
                    models.ManyToManyField(
                        blank=True, related_name="Social_image", to="media.image"
                    ),
                ),
            ],
        ),
    ]
