# Generated by Django 5.0.6 on 2024-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps_services", "0003_delete_project"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ongoing", "Ongoing"), ("completed", "Completed")],
                        max_length=20,
                    ),
                ),
                ("commencement", models.CharField(max_length=255)),
                (
                    "image",
                    models.ManyToManyField(
                        blank=True, related_name="project", to="media.image"
                    ),
                ),
                (
                    "service",
                    models.ManyToManyField(
                        related_name="Project_Service", to="apps_services.services"
                    ),
                ),
            ],
        ),
    ]
