# Generated by Django 5.0.6 on 2024-07-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_city_project_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
