# Generated by Django 5.0.6 on 2024-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_latitude_project_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(null=True),
        ),
    ]
