# Generated by Django 5.0.6 on 2024-07-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps_services", "0002_services"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
