# Generated by Django 5.0.6 on 2024-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps_home", "0001_initial"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="Award_image", to="media.image"
            ),
        ),
    ]
